name: mekanly_com
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc:
  dartz:
  equatable:
  shared_preferences:
  get_it:
  http:
  flutter_localizations:
    sdk: flutter
  intl:
  localization:
  get:
  chalkdart:
  fluttertoast:
  flutter_svg:
  flutter_native_splash: ^2.3.10
  flutter_rating_bar: ^4.0.1
  carousel_slider: ^4.2.1
  table_calendar: ^3.0.9
  image_picker:
  photo_view: ^0.15.0
  turkmen_localization_support: ^0.0.5
  change_app_package_name: ^1.2.0
  http_parser: ^4.0.2
  url_launcher: ^6.2.2
  dotted_border: ^2.1.0
  flutter_staggered_grid_view: ^0.7.0
  transparent_image: ^2.0.1
  connectivity_plus: ^5.0.2
  flutter_image_compress: ^2.2.0
  path: ^1.8.3
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/icons/
    - assets/comment.txt
    - assets/legals.txt
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 500

flutter_native_splash:
  background_image: "assets/images/screen.png"
  android_12:
  fullscreen: true
